name: data_visualization
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - altair
    - pandas
    - vega
    - vega-datasets
    - jupyter
    - pyarrow
    - fastparquet
    - openpyxl
    - geopandas
    - mnist
